# Generated by Django 4.2.25 on 2026-01-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0095_fix_related_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="dimension",
            field=models.CharField(
                choices=[("2d", "DIM_2D")],
                default="2d",
                max_length=2,
            ),
        ),
    ]
